config/routes.rb
Caddev::Application.routes.draw do

  resources :events

  resources :subjects
  resources :tutors
  resources :users

  resources :study_groups do
    resources :study_group_posts do
      resources :study_group_comments do
      end
    end
  end  
  resources :students
  resources :tutor_reviews
  resources :study_group_registrations

    # get 'study_groups/' => "study_groups#index", :as => :study_groups
    # get 'study_groups/:id' => "study_groups#show"

  get "sessions/new", :as => :sign_in
  get "signout" => 'sessions#destroy', :as => :sign_out
  post "sessions/create"

  get 'pages/sample' => "pages#sample", :as => :sample
  
  root to: 'pages#home'
end

app/models/distance.rb
class Distance < ActiveRecord::Base
  attr_accessible :col_zip, :kms, :row_zip
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :all_day, :descrition, :ends_at, :starts_at, :study_group_id, :title
  
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :tutor_id
  belongs_to :tutor
end

app/models/major_subject_area.rb
class MajorSubjectArea < ActiveRecord::Base
  attr_accessible :name
  
  has_many :subjects, :dependent => :destroy
  has_many :study_groups, :through => :subjects
  has_many :tutors, :through => :study_groups
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :user_id
  
  belongs_to :user
  
  has_many :study_groups, :through => :study_group_registrations
  has_many :study_group_registrations, :dependent => :destroy
  has_many :tutors, :through => :study_groups
  has_many :subjects, :through => :study_groups
  has_many :tutor_reviews
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/study_group.rb
class StudyGroup < ActiveRecord::Base
  attr_accessible :tutor_id, :subject_id

  
  belongs_to :tutor
  belongs_to :subject
  has_many :study_group_registrations, :dependent => :destroy
  has_many :students, :through => :study_group_registrations
  has_many :study_group_posts, :dependent => :destroy
  has_many :study_group_comments, :through => :study_group_posts
end

app/models/study_group_comment.rb
class StudyGroupComment < ActiveRecord::Base
  attr_accessible :body, :comment_id, :study_group_post_id, :user_id
  
  belongs_to :study_group_post
  belongs_to :user
end

app/models/study_group_post.rb
class StudyGroupPost < ActiveRecord::Base
  attr_accessible :body, :study_group_id, :title, :user_id
  
  has_many :study_group_comments, :dependent => :destroy
  belongs_to :user
  belongs_to :study_group
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name, :major_subject_area_id
  
  belongs_to :major_subject_area
  has_many :study_groups
  has_many :tutors, :through => :study_groups
  has_many :students, :through => :study_group_registrations
  
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  attr_accessible :account_id, :calendar_id, :user_id, :tutor_welcome
  
  belongs_to :user
  has_many :study_groups, :dependent => :destroy
  has_many :subjects, :through => :study_groups
  has_many :students, :through => :study_groups
  has_many :tutor_reviews
  has_many :tutor_review_replies
  has_many :tutor_materials
  has_many :faqs
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/tutor_material.rb
class TutorMaterial < ActiveRecord::Base
  attr_accessible :description, :tutor_id
  
  belongs_to :tutor
  
end

app/models/tutor_review.rb
class TutorReview < ActiveRecord::Base
  attr_accessible :review_text, :stars, :student_id, :tutor_id
  
  
  belongs_to :tutor
  belongs_to :student
  has_one :tutor_review_reply
end

app/models/tutor_review_reply.rb
class TutorReviewReply < ActiveRecord::Base
  attr_accessible :explanation_text, :tutor_id, :tutor_review_id
  
  belongs_to :tutor
  belongs_to :tutor_review
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :email, :street, :state, :city, :zip
  has_secure_password
  
  def zipcode
    return Zipcode.find_by_code( self.zip.to_s )
  end
  
  # destroy the tutor or student associated with this user if the user is destroyed
  has_one :tutor, :dependent => :destroy
  has_one :student, :dependent => :destroy
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  attr_accessible :city, :code, :state, :latitude, :longitude
  
  def self.distance( zip1, zip2 )
    if zip1.nil?
      puts "bad zip1"
      return 0
    end
    if zip2.nil?
      puts "bad zip2"
      return 0
    end
    if zip1.code < zip2.code
      d = Distance.find_by_row_zip_and_col_zip( zip1.code, zip2.code )
    else
      d = Distance.find_by_row_zip_and_col_zip( zip2.code, zip1.code )
    end
  
    # if we have already added to db
    
    fRkm = 6371
    nRAD_PER_DEG = 0.017453293
    
    lon1 = -zip1.longitude
    lon2 = -zip2.longitude
    lat1 = zip1.latitude
    lat2 = zip1.latitude
    
    # calculate
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    dlon_rad = dlon * nRAD_PER_DEG
    dlat_rad = dlat * nRAD_PER_DEG
    lat1_rad = lat1 * nRAD_PER_DEG
    lon1_rad = lon1 * nRAD_PER_DEG
    lat2_rad = lat2 * nRAD_PER_DEG
    lon2_rad = lon2 * nRAD_PER_DEG
    # puts "dlon: #{dlon}, dlon_rad: #{dlon_rad}, dlat: #{dlat}, dlat_rad: #{dlat_rad}"
    a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
    c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

    dKm = fRkm * c             # delta in kilometers


    if !d
      if zip1.code < zip2.code
        d = Distance.create( :row_zip => zip1.code, :col_zip => zip2.code, :kms => dKm )
      else
        d = Distance.create( :row_zip => zip2.code, :col_zip => zip1.code, :kms => dKm )
      end
    else 
      d.kms = dKm
      d.save
    end
    return d.kms
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @home_page = true
  end
  
  def home
    @home_page = true
    
    @subjects = []
    Subject.all.each do |s|
      @subjects << s.name
    end
    puts "#{@subjects}"
  end


end

app/controllers/study_groups_controller.rb
class StudyGroupsController < ApplicationController
  def index
    if params[:subject].present? && params[:location].present?
      @search_zip = Zipcode.find_by_code(params[:location])
      @subject = Subject.find_by_name(params[:subject])
      if @search_zip.nil?
        flash[:notice] = "No results for zipcode = #{params[:location]}"
        redirect_to root_url
      elsif @subject.nil?
        flash[:notice] = "No results for subject = #{params[:subject]}"
        redirect_to root_url
      end
      
      @study_groups = StudyGroup.find_all_by_subject_id( @subject.id )

      if @study_groups.count == 0
        flash[:notice] = "No results for subject = #{params[:subject]} location = #{params[:location]}"
        redirect_to root_url
      end
      else
      @study_groups = StudyGroup.find(:all, :limit=>1000)
      end 
  end

  def show
    @study_group = StudyGroup.find_by_id(params[:id])
    @tutor= @study_group.tutor
    
  end

  def update
  end

  def new
  end

  def create
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      User.find_by_id(session[:uid])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/study_groups_helper.rb
module StudyGroupsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/study_groups/_faqs.html.erb
<ul>
  <% @tutor.faqs.each do |faq|%>
  <li>Q: <%= faq.question%>
      A: <%= faq.answer%></li><br>
  <%end%>
</ul>

app/views/study_groups/_reviews.html.erb
<ul>
	<% @tutor.tutor_reviews.each do |review| %>
  <li><%= review.review_text %></li>    
    <li>Posted by <%= review.student.user.name %></li>    
    <li>on <%= review.created_at %></li><br/>
    <%end%>
</ul>

app/views/study_groups/_students.html.erb
<ul>
  <% @tutor.students.each do |student| %>
  <li><%=student.name%></li><br>
  <%end%>
</ul>

app/views/study_groups/index.html.erb
<div style="margin-top: 100px">
</div>
<h2>Search Results for: "<%= @subject.name %>" </h2>
<br></br>


<!-- Tabbable connent -->
<div class="tabbable tutor_profile_page"> 
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-user"></i>  Tutors</a></li>
    <li><a href="#tab2" data-toggle="tab"><i class="icon-folder-open"></i>  Classes</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <table class="table table-striped", id="study_groups_table">
	   <!-- you've broken the javascript study_groups.js - rem to fix -->
						

			  <tbody>
			    <% i = 10000 %>
			    <% @study_groups.each do |sg| %>
			      <tr>
			        <% if i == 0%>
				      <td><%= image_tag "/assets/miyagi_profile.jpg", :size => "85x85" %></td>
				        <!-- <img src="/images/miyagi_profile.jpg" alt="tutor profile pic"> -->
				        <td><%= link_to sg.tutor.user.name, tutor_url(sg.tutor) %></br>
  				          <%= "Santa Barbara, CA. 93132" %></br>
  				        <!--  <%= link_to "#{sg.subject.name}", study_group_url(sg) %></br> -->
  				      </td>
				        <% i = 1+1 %>
			        <% else %>
			        <td><%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "85x85" %></td>
			        <td><%= link_to "#{sg.tutor.user.name}", tutor_url(sg.tutor) %></br>
				          <%= "#{sg.tutor.user.city}, #{sg.tutor.user.state}. #{sg.tutor.user.zip}" %></br>
				        <!--  <%= link_to "#{sg.subject.name}", study_group_url(sg) %></br> -->
				      </td>
			        <% end %>
			        
			       
			        
			        <td>
				          <%= "£#{sg.cost_per_hour} per hour" %></br>
				          <%= "#{Zipcode.distance(sg.tutor.user.zipcode, @search_zip ).to_i} km away" %></br>
				        
				          <% if session[:uid].present? %>
					        <%= link_to "button to register", new_study_group_registration_url(:study_group_id =>    sg.id) %></td>
					        <%else%>
					          <%= button_to "Sign In to Register", sign_in_url, :method => "get" %>
					          <!-- <%=link_to "Sign In to Register", sign_in_url%> -->
					        <% end %>
				
				      
			      </tr>
			    <% end %>
			  </tbody>
			</table>
    </div>
    <div class="tab-pane" id="tab2">
			<table class="table table-striped", id="study_groups_table">
	   <!-- you've broken the javascript study_groups.js - rem to fix -->
						

			  <tbody>
			    <% @study_groups.each do |sg| %>
			      <tr>
				      <td><%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "85x85" %></td>
				        <!-- <img src="/images/miyagi_profile.jpg" alt="tutor profile pic"> -->
			        
			        <td class="class-title"><p class="title"><%= link_to "#{sg.subject.name} Lessons", study_group_url(sg) %></p>
			            <p>taughtby <%= link_to "#{sg.tutor.user.name}", tutor_url(sg.tutor) %></p>
				          <%= "#{sg.tutor.user.city}, #{sg.tutor.user.state}. #{sg.tutor.user.zip}" %></br>
				          
				      </td>
			       
			        
			        <td>
				          <%= "£#{sg.cost_per_hour} per hour" %></br>
				          <%= "#{Zipcode.distance(sg.tutor.user.zipcode, @search_zip ).to_i} km away" %></br>
				        
				          <% if session[:uid].present? %>
					        <%= link_to "button to register", new_study_group_registration_url(:study_group_id =>    sg.id) %></td>
					        <%else%>
					          <%= button_to "Sign In to Register", sign_in_url, :method => "get" %>
					          <!-- <%=link_to "Sign In to Register", sign_in_url%> -->
					        <% end %>
				
				      
			      </tr>
			    <% end %>
			  </tbody>
			</table>
      
    </div>
  </div>
</div>


<!-- <div class="tab-content">
  <div class="tab-pane active" id="tab1">
    <table class="table table-bordered", id="study_groups_table">
						<!--   <thead>
						    <td>Class Name</td>
						    <td>Taught By</td>
						    <td>City</td>
						    <td>Zipcode</td>
						    <td>Distance</td>
						    <td>Students</td>
						    <td>Spots Open</td>
						    <td>Cost</td>
						    <td>Register</td>
						  </thead> 

		  <tbody>
		    <% @study_groups.each do |sg| %>
		      <tr>
		        <td><%= link_to "#{sg.subject.name}", study_group_url(sg) %></td>
		        <td><%= link_to "#{sg.tutor.user.name}", tutor_url(sg.tutor) %></td>
		        <td><%= "#{sg.tutor.user.city}, #{sg.tutor.user.state}" %></td>
		        <td><%= "#{sg.tutor.user.zip}" %></td>
		        <td><%= "#{Zipcode.distance(sg.tutor.user.zipcode, @search_zip ).to_i}" %></td>
		        <td><%= "#{sg.students.count}" %></td>
		        <td><%= "#{sg.student_limit-sg.students.count}" %></td>
		        <td><%= "#{sg.cost_per_hour}" %></td>
		        <% if session[:uid].present? %>
		          <td><%= link_to "button to register", new_study_group_registration_url(:study_group_id =>    sg.id) %></td>
		        <%else%>
		          <td><%=link_to "Sign In to Register", sign_in_url%></td>
		        <% end %>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
  </div>
  <div class="tab-pane" id="tab2">
    <p>Howdy, I'm in Section 2.</p>
  </div>
</div>
</div> -->

app/views/study_groups/new.html.erb
<h1>StudyGroups#new</h1>
<p>Find me in app/views/study_groups/new.html.erb</p>

app/views/study_groups/show.html.erb
<h1>StudyGroups#show</h1>

<div>
	<h1><%= @study_group.subject.name %></h1> 
	<td><%= link_to "Back to study groups", study_groups_url %></td>
	<p>Taught by <%= link_to "#{@study_group.tutor.user.name}", tutor_url(@study_group.tutor) %></p> 
    <%="#{@study_group.student_limit-@study_group.students.count}" %> seats available	
	<td><%=link_to "Sign In to Register", sign_in_url%></td>
	
	<h3>Students </h3> 
	<% @tutor.students.each do |student| %>
		<p><li><%=student.name%> |</li></p>
	<%end%>
	
	<h3>Cost per hour</h3>
	<p><%= number_to_currency(@study_group.cost_per_hour) %></p>

	
  
  <h3>Syllabus</h3> 
  <p><%= @study_group.syllabus%></p> 
</div>

<h3>Posts</h3> 
	<div id="newpost">
	  <%= link_to "New post", new_study_group_study_group_post_path(@study_group.id), :remote => true %>
	</div>
	
	<div id="allposts"> 
	  <% @study_group.study_group_posts.each do |post| %>
	    <%= post.title%></p>
	    <%= post.body%></p>
		  <% post.study_group_comments.each do |comment| %>
        <%= comment.user.name%> <%= comment.body%> | <%= comment.created_at%>
		  <%end%>
	</div>
	
	<div class="newcomment">
		  <%= puts "Post = '#{post.id}'"%>
      <% @study_group_comment = post.study_group_comments.build %>
      <%= form_for [@study_group, post, @study_group_comment] do |t| %>
        <%= t.hidden_field :user_id, :value =>986 %>
  </div>
  
  <div class="field">
  	  <%= t.label :new_comment%><br />
  	  <%= t.text_field :body %>
	</div>
  <div class="actions">
  	  <%= t.submit %>
  </div>
      <%end%>
    <%end%>
		
		
		
		