config/routes.rb
Caddev::Application.routes.draw do

  resources :events

  resources :subjects
  resources :tutors
  resources :users

  resources :study_groups do
    resources :study_group_posts do
      resources :study_group_comments do
      end
    end
  end  
  resources :students
  resources :tutor_reviews
  resources :study_group_registrations

    # get 'study_groups/' => "study_groups#index", :as => :study_groups
    # get 'study_groups/:id' => "study_groups#show"

  get "sessions/new", :as => :sign_in
  get "signout" => 'sessions#destroy', :as => :sign_out
  post "sessions/create"

  get 'pages/sample' => "pages#sample", :as => :sample
  
  root to: 'pages#home'
end

app/models/distance.rb
class Distance < ActiveRecord::Base
  attr_accessible :col_zip, :kms, :row_zip
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :all_day, :descrition, :ends_at, :starts_at, :study_group_id, :title
  
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :tutor_id
  belongs_to :tutor
end

app/models/major_subject_area.rb
class MajorSubjectArea < ActiveRecord::Base
  attr_accessible :name
  
  has_many :subjects, :dependent => :destroy
  has_many :study_groups, :through => :subjects
  has_many :tutors, :through => :study_groups
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :user_id
  
  belongs_to :user
  
  has_many :study_groups, :through => :study_group_registrations
  has_many :study_group_registrations, :dependent => :destroy
  has_many :tutors, :through => :study_groups
  has_many :subjects, :through => :study_groups
  has_many :tutor_reviews
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/study_group.rb
class StudyGroup < ActiveRecord::Base
  attr_accessible :tutor_id, :subject_id

  
  belongs_to :tutor
  belongs_to :subject
  has_many :study_group_registrations, :dependent => :destroy
  has_many :students, :through => :study_group_registrations
  has_many :study_group_posts, :dependent => :destroy
  has_many :study_group_comments, :through => :study_group_posts
end

app/models/study_group_comment.rb
class StudyGroupComment < ActiveRecord::Base
  attr_accessible :body, :comment_id, :study_group_post_id, :user_id
  
  belongs_to :study_group_post
  belongs_to :user
end

app/models/study_group_post.rb
class StudyGroupPost < ActiveRecord::Base
  attr_accessible :body, :study_group_id, :title, :user_id
  
  has_many :study_group_comments, :dependent => :destroy
  belongs_to :user
  belongs_to :study_group
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name, :major_subject_area_id
  
  belongs_to :major_subject_area
  has_many :study_groups
  has_many :tutors, :through => :study_groups
  has_many :students, :through => :study_group_registrations
  
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  attr_accessible :account_id, :calendar_id, :user_id, :tutor_welcome
  
  belongs_to :user
  has_many :study_groups, :dependent => :destroy
  has_many :subjects, :through => :study_groups
  has_many :students, :through => :study_groups
  has_many :tutor_reviews
  has_many :tutor_review_replies
  has_many :tutor_materials
  has_many :faqs
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/tutor_material.rb
class TutorMaterial < ActiveRecord::Base
  attr_accessible :description, :tutor_id
  
  belongs_to :tutor
  
end

app/models/tutor_review.rb
class TutorReview < ActiveRecord::Base
  attr_accessible :review_text, :stars, :student_id, :tutor_id
  
  
  belongs_to :tutor
  belongs_to :student
  has_one :tutor_review_reply
end

app/models/tutor_review_reply.rb
class TutorReviewReply < ActiveRecord::Base
  attr_accessible :explanation_text, :tutor_id, :tutor_review_id
  
  belongs_to :tutor
  belongs_to :tutor_review
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :email, :street, :state, :city, :zip
  has_secure_password
  
  def zipcode
    return Zipcode.find_by_code( self.zip.to_s )
  end
  
  # destroy the tutor or student associated with this user if the user is destroyed
  has_one :tutor, :dependent => :destroy
  has_one :student, :dependent => :destroy
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  attr_accessible :city, :code, :state, :latitude, :longitude
  
  def self.distance( zip1, zip2 )
    if zip1.nil?
      puts "bad zip1"
      return 0
    end
    if zip2.nil?
      puts "bad zip2"
      return 0
    end
    if zip1.code < zip2.code
      d = Distance.find_by_row_zip_and_col_zip( zip1.code, zip2.code )
    else
      d = Distance.find_by_row_zip_and_col_zip( zip2.code, zip1.code )
    end
  
    # if we have already added to db
    
    fRkm = 6371
    nRAD_PER_DEG = 0.017453293
    
    lon1 = -zip1.longitude
    lon2 = -zip2.longitude
    lat1 = zip1.latitude
    lat2 = zip1.latitude
    
    # calculate
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    dlon_rad = dlon * nRAD_PER_DEG
    dlat_rad = dlat * nRAD_PER_DEG
    lat1_rad = lat1 * nRAD_PER_DEG
    lon1_rad = lon1 * nRAD_PER_DEG
    lat2_rad = lat2 * nRAD_PER_DEG
    lon2_rad = lon2 * nRAD_PER_DEG
    # puts "dlon: #{dlon}, dlon_rad: #{dlon_rad}, dlat: #{dlat}, dlat_rad: #{dlat_rad}"
    a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
    c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

    dKm = fRkm * c             # delta in kilometers


    if !d
      if zip1.code < zip2.code
        d = Distance.create( :row_zip => zip1.code, :col_zip => zip2.code, :kms => dKm )
      else
        d = Distance.create( :row_zip => zip2.code, :col_zip => zip1.code, :kms => dKm )
      end
    else 
      d.kms = dKm
      d.save
    end
    return d.kms
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
	before_filter :require_login, :only => [:edit, :update]
	def index
	  @tutors = Tutor.find(:all)
	  @subjects = MajorSubjectArea.find(:all)
	  @tutors = Tutor.page(params[:page]).per(10)
	end

	def edit
		@tutor = Tutor.find_by_id(params[:id])
	end

	def update
		tutor = Tutor.find_by_id(params[:id])
		tutor.update_attributes(params[:tutor])
		redirect_to "/tutors/#{tutor.id}"
	end

	def show
	  
		@tutor = Tutor.find_by_id(params[:id])
		@tutor_zipcode = Zipcode.find_by_code( @tutor.user.zip.to_s)
		#how do i set different background images
		@tutor_show = true
		@study_groups = StudyGroup.find_all_by_tutor_id(@tutor)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      User.find_by_id(session[:uid])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/study_groups_helper.rb
module StudyGroupsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tutors/_profile.html.erb
<div class="profile">
  <h3>Welcome</h3>
  <p><%= @tutor.tutor_welcome %></p>
  <h3>Questions & Answers</h3>
  <p><em>Q: What you gonna do when they come for you?</em></p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p><em>Q: What you gonna do when they come for you?</em></p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p><em>Q: What you gonna do when they come for you?</em></p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p><em>Q: What you gonna do when they come for you?</em></p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


  <div class = "google_map span6">
    <div id="map_canvas" data-latitude = '<%= "#{@tutor_zipcode.latitude}" %>' data-longitude = '<%= "#{@tutor_zipcode.longitude}" %>'>
    </div>
  </div>
</div>

app/views/tutors/_students.html.erb
<div>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
</div>

app/views/tutors/_syllabus.html.erb
<div class = "profile">
<h3>What you'll learn</h3>
<p><em>Step 1: Waxing</em></p>
 <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
 <p><em>Step 2: Sanding</em></p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p><em>Step 3: Painting</em></p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p><em>Step 4: The Crane</em></p>
      <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
  <!-- <h3>What you'll learn</h3>
   <p><em>Step 1: Waxing</em></p>
   <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

   <p><em>Step 2: Sanding/em></p>
   <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

   <p><em>Step 3: Painting</em></p>
   <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

   <p><em>Step 4: The Crane</em></p>
   <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> -->

app/views/tutors/_unused.html.erb
   <!-- <#% if session[:uid].present? %>

     <table class="table table-bordered", id="study_groups_table">
       <thead>
         <td>Class Name</td>
         <td>Taught By</td>
         <td>Students</td>
         <td>Spots Open</td>
         <td>Cost</td>
         <td>Register</td>
       </thead>

       <tbody>
         <%# @study_groups.each do |sg| %>
           <tr>
             <td><%#= link_to "#{sg.subject.name}", study_group_url(sg) %></td>
             <td><%#= link_to "#{sg.tutor.user.name}", tutor_url(sg.tutor) %></td>
             <td><%#= "#{sg.students.count}" %></td>
             <td><%#= "#{sg.student_limit-sg.students.count}" %></td>
             <td><%#= "#{sg.cost_per_hour}" %></td>
             <%# if session[:uid].present? %>
               <td><%#= link_to "Register Now!", new_study_group_registration_url(:study_group_id => sg.id) %></td>
             <%#else%>
               <td><%#=link_to "Sign In to Register", sign_in_url%></td>
             <%# end %>
           </tr>
         <%# end %>
       </tbody>
     </table> 

    <%#else%>
    
    <div id="sg">
     <%# @study_groups.each do |sg| %>
     <%#= link_to "#{sg.subject.name}", study_group_url(sg) %>
     </div>
     <div id="newpost">
  	 <p><%#= link_to "New post", new_study_group_study_group_post_path(sg.id), :remote => true %></p>
  	<%# end %>
  
  	</div>
  	
    <%# end %>
</div> -->

	

app/views/tutors/edit.html.erb
<h2>Edit Your Profile</h2>

<%=form_for @tutor do |f|%>
	<%=@tutor.name%>
	
	<%=f.label :profile%>
	<%=f.text_area :profile%>
	<%=f.submit%>

<%end%>

app/views/tutors/index.html.erb

<div class = "google_map" onload="google_map_initialize()">
  <div id="map_canvas"></div>
</div>

<nav>
	<ul>
		<% @subjects.each do |subject| %>
		  <li><% link_to subject.name.capitalize, subjects_url(subject) %></a></li>
		<%end%>
		<li><a href="#">Edit</a></li>
		<li><a href="#">View</a></li>
		<li><a href="#">Help</a></li>
		
	</ul>
</nav>
<% @tutors.each do |tutor| %>
	<h2><%= link_to tutor.name, tutor_url(tutor) %></h2>
	<h4><%= tutor.user.city %></h4>
	<p><%= truncate(tutor.tutor_welcome, :length => 160) %><p>
<%end%>
<%= paginate @tutors %>

app/views/tutors/show.html.erb
<div class="container">
	<div class="opaque_background">
			<div class = "container_tutor">
			  <div class="row">
			    <div class="span12">
				    <header>
			        <div class="row">
  			      	<div class="span6">
  				        <%#= image_tag "/assets/miyagi_profile.jpg", :size => "75x75" %>
  				        <%= image_tag "http://graph.facebook.com/#{Random.rand(10000)}/picture", :size => "75x75" %>
  				        <h1><%= @tutor.study_groups.first.subject.name %> Lessons</h1> <!-- Dynamic what exactly are you going to call this -->
  				        <!-- ><p class="tutor-name"><a href="http://localhost:3000">taughtby</a> <%= @tutor.user.name %><p> -->
  				        <p class="tutor-name"><a href="http://localhost:3000">taughtby</a> <%= @tutor.user.name %><p>
  					      <div class="share">
  						      <p>share:</p>
  									<img src="http://placehold.it/15x15" alt="facebook">
  									<img src="http://placehold.it/15x15" alt="twitter">
  									<img src="http://placehold.it/15x15" alt="email">
  						    </div>
  				      </div> <!-- <div class="span6"> -->
  				      <div class="fuck-off">
  			      		<div class="span4 offset2">	 
  								  <a href="#"><i class="icon-envelope icon-white"></i>Contact Me</a>
    								<p class="contact-details"><%= render 'users/contact_info', :user => @tutor.user %></p>
  					      </div>
  			        </div> <!-- <div class="fuck-off"> -->
  			      </div> <!-- <div class="row"> -->
			      </header>
			    </div> <!-- <div class="span12"> -->
			  </div> <!-- row -->
			</div> <!-- end of container_tutor> -->
	
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs" id="myTab">
        <li><a href="#lA" data-toggle="tab">Profile</a></li>
        <li><a href="#lB" data-toggle="tab">Syllabus</a></li>
        <li><a href="#lE" data-toggle="tab">Reviews</a></li>
        <li><a href="#lC" data-toggle="tab">Students</a></li>
        <li><a href="#lD" data-toggle="tab">Calendar</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane" id="lA">
          <%= render 'profile' %>
    		</div> <!-- end of id="lA" -->
        <div class="tab-pane" id="lB">  
          <%= render 'syllabus' %>
    		</div> <!-- end of id="lB" -->
        <div class="tab-pane" id="lC">
          <%= render 'students'%>
          <!-- <%#= render 'study_groups/students'%> -->
        </div> <!-- end of id="lE" -->
        <div class="tab-pane" id="lD">
           <div class='calendar' data-id = '<%="#{@tutor.id}"%>' ></div>
        </div> <!-- end of id="lF" -->
      </div> <!-- end of tab-content -->
    </div> <!-- end of tabbable tabs-left -->

  </div> <!-- end of opaque background -->
</div> <!-- end of container -->
 	