config/routes.rb
Caddev::Application.routes.draw do

  resources :events

  resources :subjects
  resources :tutors
  resources :users

  resources :study_groups do
    resources :study_group_posts do
      resources :study_group_comments do
      end
    end
  end  
  resources :students
  resources :tutor_reviews
  resources :study_group_registrations

    # get 'study_groups/' => "study_groups#index", :as => :study_groups
    # get 'study_groups/:id' => "study_groups#show"

  get "sessions/new", :as => :sign_in
  get "signout" => 'sessions#destroy', :as => :sign_out
  post "sessions/create"

  get 'pages/sample' => "pages#sample", :as => :sample
  
  root to: 'pages#home'
end

app/models/distance.rb
class Distance < ActiveRecord::Base
  attr_accessible :col_zip, :kms, :row_zip
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :all_day, :descrition, :ends_at, :starts_at, :study_group_id, :title
  
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :tutor_id
  belongs_to :tutor
end

app/models/major_subject_area.rb
class MajorSubjectArea < ActiveRecord::Base
  attr_accessible :name
  
  has_many :subjects, :dependent => :destroy
  has_many :study_groups, :through => :subjects
  has_many :tutors, :through => :study_groups
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :user_id
  
  belongs_to :user
  
  has_many :study_groups, :through => :study_group_registrations
  has_many :study_group_registrations, :dependent => :destroy
  has_many :tutors, :through => :study_groups
  has_many :subjects, :through => :study_groups
  has_many :tutor_reviews
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/study_group.rb
class StudyGroup < ActiveRecord::Base
  attr_accessible :tutor_id, :subject_id

  
  belongs_to :tutor
  belongs_to :subject
  has_many :study_group_registrations, :dependent => :destroy
  has_many :students, :through => :study_group_registrations
  has_many :study_group_posts, :dependent => :destroy
  has_many :study_group_comments, :through => :study_group_posts
end

app/models/study_group_comment.rb
class StudyGroupComment < ActiveRecord::Base
  attr_accessible :body, :comment_id, :study_group_post_id, :user_id
  
  belongs_to :study_group_post
  belongs_to :user
end

app/models/study_group_post.rb
class StudyGroupPost < ActiveRecord::Base
  attr_accessible :body, :study_group_id, :title, :user_id
  
  has_many :study_group_comments, :dependent => :destroy
  belongs_to :user
  belongs_to :study_group
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name, :major_subject_area_id
  
  belongs_to :major_subject_area
  has_many :study_groups
  has_many :tutors, :through => :study_groups
  has_many :students, :through => :study_group_registrations
  
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  attr_accessible :account_id, :calendar_id, :user_id, :tutor_welcome
  
  belongs_to :user
  has_many :study_groups, :dependent => :destroy
  has_many :subjects, :through => :study_groups
  has_many :students, :through => :study_groups
  has_many :tutor_reviews
  has_many :tutor_review_replies
  has_many :tutor_materials
  has_many :faqs
  
  def name
    return self.user.name
  end
  def address
    return self.user.address
  end
end

app/models/tutor_material.rb
class TutorMaterial < ActiveRecord::Base
  attr_accessible :description, :tutor_id
  
  belongs_to :tutor
  
end

app/models/tutor_review.rb
class TutorReview < ActiveRecord::Base
  attr_accessible :review_text, :stars, :student_id, :tutor_id
  
  
  belongs_to :tutor
  belongs_to :student
  has_one :tutor_review_reply
end

app/models/tutor_review_reply.rb
class TutorReviewReply < ActiveRecord::Base
  attr_accessible :explanation_text, :tutor_id, :tutor_review_id
  
  belongs_to :tutor
  belongs_to :tutor_review
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :email, :street, :state, :city, :zip
  has_secure_password
  
  def zipcode
    return Zipcode.find_by_code( self.zip.to_s )
  end
  
  # destroy the tutor or student associated with this user if the user is destroyed
  has_one :tutor, :dependent => :destroy
  has_one :student, :dependent => :destroy
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  attr_accessible :city, :code, :state, :latitude, :longitude
  
  def self.distance( zip1, zip2 )
    if zip1.nil?
      puts "bad zip1"
      return 0
    end
    if zip2.nil?
      puts "bad zip2"
      return 0
    end
    if zip1.code < zip2.code
      d = Distance.find_by_row_zip_and_col_zip( zip1.code, zip2.code )
    else
      d = Distance.find_by_row_zip_and_col_zip( zip2.code, zip1.code )
    end
  
    # if we have already added to db
    
    fRkm = 6371
    nRAD_PER_DEG = 0.017453293
    
    lon1 = -zip1.longitude
    lon2 = -zip2.longitude
    lat1 = zip1.latitude
    lat2 = zip1.latitude
    
    # calculate
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    dlon_rad = dlon * nRAD_PER_DEG
    dlat_rad = dlat * nRAD_PER_DEG
    lat1_rad = lat1 * nRAD_PER_DEG
    lon1_rad = lon1 * nRAD_PER_DEG
    lat2_rad = lat2 * nRAD_PER_DEG
    lon2_rad = lon2 * nRAD_PER_DEG
    # puts "dlon: #{dlon}, dlon_rad: #{dlon_rad}, dlat: #{dlat}, dlat_rad: #{dlat_rad}"
    a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
    c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

    dKm = fRkm * c             # delta in kilometers


    if !d
      if zip1.code < zip2.code
        d = Distance.create( :row_zip => zip1.code, :col_zip => zip2.code, :kms => dKm )
      else
        d = Distance.create( :row_zip => zip2.code, :col_zip => zip1.code, :kms => dKm )
      end
    else 
      d.kms = dKm
      d.save
    end
    return d.kms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      User.find_by_id(session[:uid])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "TaughtBy", root_url, :class => "brand" %>
        <ul class="nav">
	
				<% if session[:uid].present? %>
					<li><%= link_to "View My Profile", student_url(current_user) %></li>
					<li><%= link_to "Sign Out", sign_out_url %></li>
				<% else %>
					<li class="divider-vertical"></li>
					<!-- the marketing bit get rid if no time -->
					<li><%= link_to "How It Works", "#" %></li>
					
					<li class="divider-vertical"></li>
					<li><%= link_to "Sign Up", new_user_url %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to "Login", sign_in_url %></li>
					<li class="divider-vertical"></li>
					
					<!-- need to add some kind of search for site
					<ul class="nav pull-right">
						<form class="navbar-search">
						  <input type="text" class="search-query" placeholder="Search">
						</form>
					</ul> -->
					
				<% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caddev</title>
  
  <script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCwkz6dUGGl47j3qhO4VcxAcFYEj0A9lKg&sensor=false">
  </script>
	

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head> 
<!-- gets rid of the nav bar on tutor_show -->
<%= render 'layouts/header' unless (controller.controller_name == "tutors") && (controller.action_name == "show") %>

<!-- trying to set different background images for home page and tutor_show -->
<body class="<%= params[:controller] %>">
	<div class="container">
    <%= yield %>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="container home_page">
	
	<% if flash[:notice] %>
		<h3 class="prepend-1"><%= flash[:notice] %></h1>
	<% end %>
	
	<div class="row">
		
		<div class="span8 offset2">
			<div class="center">
			<br></br><!-- get rid of this after styling -->
			<br></br>
			<br></br><!-- get rid of this after styling -->
				<h1>Learn Something New!</h1>
			  <h2>Find the best tutors and classes in your city</h2>
			<br></br><!-- get rid of this after styling -->
			
		    <div class="hero-unit">

	
			  
		        <% complete_list = ["guitar", "piano"] %>
						<%= form_tag study_groups_url, :method => 'get', :class => "prepend-3" do %>
								<label>I want to learn...</label>
								<%= text_field_tag 'subject', nil, :id => "search-subject", :class => "span6 search-query",
								 :autocomplete => "off", :placeholder=>"a subject...", :data => {:provide => "typeahead", :items=>"4", 
								   :source => @subjects }%>
							
						    <label>near...</label>
						    
						    <input id='search-location' type="text" class="span6 search-query" name='location' value='' autocomplete='off' placeholder="your zipcode">
						    <br/><br/>
								<button type="submit" class="btn btn-success btn-large">Search for your tutor</button>
						<% end %>
		
		
			  </div>
			
			
	    </div>
    </div>
  </div>
</div>



















app/views/pages/sample.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CSS Framework</title>
</head>
<body>
	<div class ="container">
		<h1 class ="span-24">
			H1 Header
		</h1>
		<div class ="span-12">
			<h2>H2 Header</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.
			</p>
			<h3 class = "span-12">H3 Header</h3>
			<div class = "span-6">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.</p>
			</div>
			<div class ="span-6 last">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.</p>
			</div>
		</div>
		<div class ="span-8">
			<h2>H2 Header</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.</p>

			<h3>H3 Header</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.</p>

		</div>
		<div class = "span-4 last">
			<h2>H2 Header</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam diam lacus, cursus et commodo eget, feugiat vestibulum quam. Sed lorem leo, malesuada sit amet tempus eu, luctus in eros. Aliquam erat volutpat. Pellentesque vel turpis a leo auctor pulvinar ac non felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque tellus. Aenean vel tellus diam, et tempus est. Proin dolor neque, viverra in laoreet eget, ornare et sem. In nec tortor id neque pellentesque volutpat eu et nunc. Duis iaculis orci eu dolor varius vel volutpat mi iaculis. Morbi vehicula, nisi in ullamcorper vehicula, sem elit imperdiet sapien, tristique sagittis nunc libero vel velit. Phasellus lobortis imperdiet est eu pretium. Curabitur enim libero, ultrices ut fringilla sed, tempus vitae sem. Duis at sem diam, eget tincidunt dui. Suspendisse tortor quam, ultrices a tincidunt eu, posuere bibendum lacus. Phasellus fermentum tortor et metus viverra vehicula.</p>
		</div>
	</div>
</body>
</html>